# Generated by Django 4.2.3 on 2023-07-26 08:49

from django.db import migrations, models
import django.db.models.deletion
import showroom.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('brand_pic', models.ImageField(upload_to=showroom.models.brand_path)),
            ],
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chasis_number', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Showroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('picture', models.ImageField(upload_to=showroom.models.staff_path)),
                ('position', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256, unique=True)),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='showroom.showroom')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('car_pic', models.ImageField(upload_to=showroom.models.car_path)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='showroom.brand')),
                ('engine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engine', to='showroom.engine')),
                ('feature', models.ManyToManyField(related_name='feature', to='showroom.feature')),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='showroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='showroom.showroom'),
        ),
    ]
