# Generated by Django 4.2.3 on 2023-07-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engine',
            name='chasis_number',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
