# Generated by Django 4.2.3 on 2023-07-27 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0003_remove_car_brand_remove_car_car_pic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engine',
            old_name='chasis_number',
            new_name='engine_number',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='engine',
        ),
        migrations.AddField(
            model_name='car',
            name='chasis_number',
            field=models.CharField(default=5, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='engine',
            field=models.OneToOneField(default=23, on_delete=django.db.models.deletion.CASCADE, related_name='engine', to='showroom.engine'),
            preserve_default=False,
        ),
    ]
